Added setForward() Command to Change Robot's Wheels from X to Forward
cachemoney8096/2023-charged-up pull request #102
Opened 2023-03-02 01:19 UTC by avakimc

* Used when it is the first path
* Has a wait command to wait for 0.1 seconds after setting the wheels to forward
* if it is not the first path, just move on

2023-03-02 01:21 UTC, tails618 requested changes
Replace the `WaitCommand` with a `.withTimeout` on the `RunCommand`, since `RunCommand` runs indefinitely.

2023-03-02 01:44 UTC, balghane approved these changes

2023-03-02 01:44 UTC, avakimc commented
/format

2023-03-03 15:32 UTC, tails618 approved these changes

2023-03-03 21:47 UTC, merged