Add a format action based on comment
cachemoney8096/2023-charged-up pull request #9
Opened 2023-01-19 19:53 UTC by balghane

This removes the auto-formatting that was happening before.

2023-01-19 20:24 UTC, tails618 requested changes

2023-01-19 20:24 UTC, tails618 commented on .github/workflows/comment_format.yml
> +          token: ${{ ssecrets.FORMATTER_PAT }}
Should be `secrets`, not `ssecrets`.

2023-01-19 20:24 UTC, tails618 commented on .github/workflows/comment_format.yml
> +          GITHUB_TOKEN: "${{ ssecrets.FORMATTER_PAT }}"
`ssecrets`

2023-01-19 23:56 UTC, balghane commented on .github/workflows/comment_format.yml
> +          token: ${{ ssecrets.FORMATTER_PAT }}
fixed

2023-01-19 23:56 UTC, balghane commented on .github/workflows/comment_format.yml
> +          GITHUB_TOKEN: "${{ ssecrets.FORMATTER_PAT }}"
fixed

2023-01-20 22:49 UTC, avakimc approved these changes

2023-01-20 22:49 UTC, avakimc commented on .github/workflows/comment_format.yml
> +name: Format PR on comment
Do I have to understand this/What is all this?

2023-01-20 22:49 UTC, avakimc commented on build.gradle
> +}
What does this do?

2023-01-20 23:53 UTC, tails618 approved these changes

2023-01-20 23:54 UTC, merged